### ISSUE TITLE
Continuous Integration Question

### ISSUE THREAD

**Issue by Reichenbachian** [willmeyers/stainless-cli#2]
Is there a reasonable way to use this in CI? I'd assume the oath would time out eventually.

**Comment by willmeyers** [comment]
No - in its current state I wouldn't recommend using this in CI. You're correct in that the session tokens will eventually time out (also a major security risk).

For using Stainless API in CI you can refer to their GitHub action: https://github.com/marketplace/actions/stainless-upload-openapi-specification.

As for implementing support for CI, it appears they have two separate endpoints for generating SDKs. I'm kind of waiting to see if they're going to offer a standard API accessible with their API tokens before trying to implement anything.

**Comment by Reichenbachian** [comment]
Makes sense. Appreciate the work so far.
